### ISSUE TITLE
REGULAR EXPRESSION REFERENCE has incorrect regex command examples.

### ISSUE THREAD

**Issue by Charles-A-Measday** [Sigil-Ebook/sigil-user-guide#1]
Sigil_User_Guide_2019.09.03.epub (and previous versions) has two incorrect regex commands in the "REGULAR EXPRESSION REFERENCE" section/"OVERVIEW"/"SINGLE CHARACTERS:".

`[:alpha:]` - should be in a bracket expression - `[[:alpha:]]`

`[^:alnum:]` - should also be in a bracket expression - `[^[:alnum:]]`

(I was puzzled by the second one and tried `[[^:alnum:]]` in Sigil.  It matches not one, but two characters: the two `:]` instances above and `a]` in the metadata tutorial, line 33.)

(First-time GitHub user)

**Comment by kevinhendricks** [comment]
Agreed,  Since we are in the process of fully updating the user guide for the upcoming Sigil 1.5.0 release, we have incorporated your suggested fix.

Thank you!
