### ISSUE TITLE
How to use Sigil?

### ISSUE THREAD

**Issue by elnath78** [Sigil-Ebook/sigil-user-guide#14]
Hello, I'm sorry but I'm lost. It looks like an HTML editor, it is not clear to me how to import my .odt or .docx file and plit it into chapters. Is it a manual operation?

**Comment by dougmassay** [comment]
It's not an HTML editor, it's an epub editor. That certainly includes the ability to edit html, but that's not it's only function.

Sigil itself does not include the ability to import .odt or .docx files. Only html, css, xml, and image files. Either convert your content to html/css and use the instructions in user guide to import it, or look into third-party Sigil plugins to directly import .odt or .docx files. The user guide includes a section on plugins (including links to where they can be found).

As to splitting files into chapters, that's included in the user guide as well.

If you're still lost, the best place to get help using Sigil is the Sigil forums on MobileRead.com. Links to Mobileread can also be found in the user guide.

Have you read the user guide?

**Comment by elnath78** [comment]
@dougmassay I checked the documentation on the website (https://sigil-ebook.com/sigil/guide/) but there is not much to guide me, no step by step. Also I thought there was some sort of "template" to apply to various elements, like heading, pragraph and every embelishment such as styles to apply to them. I thought Sigil was to be used to apply a style other than save as epub.

**Comment by elnath78** [comment]
I just saw the big green button! Thought it was still for Sigil download and didnt pay attention. Why not publish it on KDP for free?

**Comment by dougmassay** [comment]
Because KDP is for Kindle books. We have no problem with people making Kindlebooks from Sigil EPUBs, but Sigil is, after all, an EPUB editor and not a Kindlebook editor/creator.

People looking to make EPUBs with Sigil are expected to have at least a passing knowledge of the EPUB structure (as well as being familiar with HTML/CSS).

Sigil is not intended to be a turnkey, wysiwyg ebook creator. Some assembly is expected/required.

**Comment by dougmassay** [comment]
And GitHub (where everything--including the Sigil website is currently hosted) is also free. I have no interest in joining or using KDP.

**Comment by elnath78** [comment]
How about basic templates/preset? Featuring a few styles could help start. I donwloaded the guide, it is broad, but what are the essential steps before publishing? In particular do I need to edit toc.ncx and content.opf files?

**Comment by dougmassay** [comment]
There are no definitive "steps to take before publishing" because everyone's publishing needs/workflows are different.

This is simply not the place to learn how to use Sigil. Join the user forum (in the guide) if you need help. The link is in the user guide and on the website.

**Comment by kevinhendricks** [comment]
You might want to check out a few of the tutorials in the users guide:

Such as  tutorial_convert_to_html.xhtml and others in your epub reader or in Sigil or PageEdit, or any decent epub3 reader.

Closing this.
