### ISSUE TITLE
minor typo

### ISSUE THREAD

**Issue by bartoncreek** [Sigil-Ebook/sigil-user-guide#18]
##### Correction: strike _be_:

> `29: <p>`The text you enter as the name to use in the Index will  **~~be~~**[^1]  show up in the Index as follows:`<\p>`

*****

[^1]: https://github.com/Sigil-Ebook/sigil-user-guide/blob/013e6059f86c494acde999ebf8473376f5777fcc/src/OEBPS/Text/indexes.xhtml#L29

**Comment by kevinhendricks** [comment]
Thank you.  I will fix this when the next set of updates are made to the user guide.

**Comment by kevinhendricks** [comment]
This has now been fixed in master.

Thank you.
