### ISSUE TITLE
Broken link in chapter "FAQ"

### ISSUE THREAD

**Issue by OdinZa** [Sigil-Ebook/sigil-user-guide#19]
Hello.

In the process of working on the translation, a broken link was found:
file faq.xhtml 
section "Formatting and Styles", question "Why does my book display random question marks?", link to "Adobe PDF Reference v1.7"

broken: https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf
working: https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/pdfreference1.7old.pdf

Please correct.

**Comment by kevinhendricks** [comment]
Thanks.

Will do.

**Comment by kevinhendricks** [comment]
This has now been fixed in master.

Thank you.
