### ISSUE TITLE
I think that these are inaccuracies and typos.

### ISSUE THREAD

**Issue by OdinZa** [Sigil-Ebook/sigil-user-guide#20]
Hello.

Finished the translation of the chapter "Tutorials" from the Guide.
Along the way, I compiled a list that included, as I think, various inaccuracies and typos. See for yourself:

File: about_epub.xhtml
extra closing bracket
Your EPUB stores your words and text in the book using the an XML form called XHTML of the HTML format (Hyper Text Markup Language) – the same code used by web pages to display text and images).

TUTORIAL

File: tutorial_getting_started_with_epub.xhtml
probably Right-To-Left
EPUB3 EPUBs are quickly becoming the international publishing standard as they support both Right-To_Left (RTL) and Left-To_Right (LTR) text layout,

File: tutorial_embed_fonts.xhtml
no closing quote in title
@font-face {
    font-family: 'Garamond ;

File: tutorial_save.xhtml
extra colon after File=&gt;Save:
<p>To save your EPUB, click the Save icon <img alt="Showing File Save icon." src="../Images/document-save.png"/> or use the menu item <span class="menuitem">File=&gt;Save:</span> or the keyboard shortcut – Ctrl+S <a href="#section1">[1]</a></p>

File: tutorial_load_file.xhtml
extra colon after File=&gt;Open</span>:
<p>To load your HTML or EPUB file into Sigil, click the Open icon <img alt="File Open menu" src="../Images/document-open.png"/> or use the menu item <span class="menuitem">File=&gt;Open</span>: or the keyboard shortcut Ctrl+O</p>

File: tutorial_add_cover.xhtml
double tag <span class="menuitem"></span>
<p>To add a cover, just select the menu item <span class="menuitem"><span class="menuitem">Tools=&gt;Add Cover</span></span></p>

in these paragraphs, swap the colon and period at the end of sentences
<p>And that’s it. Sigil has added your image to the EPUB and marked it as the cover image. It has also created an HTML file at the start of your book and inserted your cover image into the file so that it will be displayed at the start of the book:</p>
<p>The contents of your Book Browser show that the cover.xhtml file has been added to the Text folder, and the cover.jpg image has been added to the Images folder.</p>

File: tutorial_mark_chapters.xhtml
a colon at the end of a paragraph instead of a period
<p>In order to create a Table of Contents you need to tell Sigil what your chapter names are. To do this just select each chapter name in your book and use one of the toolbar buttons to mark it as a chapter heading:</p>

File: tutorial_spelling.xhtml
instead of Case-Insensitive Sort it should be Locale-Aware Sort or this line refers to another topic altogether
<li><span class="listheading">Case-Insensitive Sort:</span> Enable this to sort words as AaBbCc instead of ABCabc.</li>

File: tutorial_find_replace.xhtml
different words are used in the examples on the pictures in the section "Using Find &amp; Replace"

File: tutorial_advanced_find.xhtml
in the tutorial-find-regex-chapter.png picture, the mode is "Normal" instead of "Regex"

**Comment by OdinZa** [comment]
Strange. The text did not display correctly.
Here is the text file.
[err.txt](https://github.com/Sigil-Ebook/sigil-user-guide/files/10713110/err.txt)

**Comment by kevinhendricks** [comment]
Thanks for those corrections.  I will incorporate those fixes into the next release of the user guide.

**Comment by kevinhendricks** [comment]
These should now all be fixed in master.

Thank you!
