### ISSUE TITLE
inaccuracies and typos - part 2

### ISSUE THREAD

**Issue by OdinZa** [Sigil-Ebook/sigil-user-guide#21]
This is a work in progress, and the second part of the typos in the text of the Guide has already appeared.
I will immediately upload a text file with errors. Please check it.
[err-2.txt](https://github.com/Sigil-Ebook/sigil-user-guide/files/10825982/err-2.txt)

**Comment by kevinhendricks** [comment]
Thanks.  Will do upon my return in about 2 weeks.  I am travelling.

**Comment by kevinhendricks** [comment]
Ah!  I see that the colon is being used inconsistently and that is a bug.  I will look into the best way to make things more consistent.

**Comment by kevinhendricks** [comment]
Question:  In what way inside spellcheck.xhtml is their an "extra" image of the context menu.  It only appears once.  src="../Images/spellcheck-editor-dictionaries.png"?

**Comment by kevinhendricks** [comment]
These will be fixed in master except for the one Question see above.  I will leave this open to make sure this gets followed up.

**Comment by OdinZa** [comment]
Hello.

Regarding the image in Spellcheck:

The text describes the elements of the "Spellcheck" window, which is presented above.

And you give the image in the text, which refers to the pop-up menu in the "Code View" window.
in lines 78 - 80
```
<div class="image">
    <img alt="SpellCheck Dialog adding words to dictionaries." src="../Images/spellcheck-editor-dictionaries.png"/>
  </div>
```
Therefore, this image is superfluous here.

**Comment by dougmassay** [comment]
That seems like a judgement call to me. Not an inaccuracy or a typo.

**Comment by kevinhendricks** [comment]
Agreed.  We'll just leave it be then.
Closing this.

**Comment by OdinZa** [comment]
It's clear.

In the Russian version of the manual, I removed this picture.
And I also replaced one of the not entirely clear tips with **Doitsu's** answer: https://www.mobileread.com/forums/showpost.php?p=4294658&postcount=139

Now I'm thinking of adding **BeckyEbook** tips:
https://www.mobileread.com/forums/showpost.php?p=4297619&postcount=164
and
https://www.mobileread.com/forums/showpost.php?p=4306835&postcount=14

I consider them very important and useful.
