### ISSUE TITLE
inaccuracies and typos - part 3

### ISSUE THREAD

**Issue by OdinZa** [Sigil-Ebook/sigil-user-guide#22]
Finished the translation of the User's Guide.
This is the last batch of inaccuracies and typos.
I immediately upload a text file with errors. Please check it out.

[err-3.txt](https://github.com/Sigil-Ebook/sigil-user-guide/files/10890878/err-3.txt)

**Comment by kevinhendricks** [comment]
Still traveling but will do so upon my return.

Thank you.

**Comment by kevinhendricks** [comment]
These will be fixed in master with the next push.
