### ISSUE TITLE
Can't save

### ISSUE THREAD

**Issue by jimhenry2** [Sigil-Ebook/sigil-user-guide#3]
Suddenly having several issues.  What does this mean:
Error info: Cannot save file C:/Users/Jim Henry/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/LocalState/Files/S0/10/Attachments/A Right where you're supposed to be - Ran Register[165].epub: C:/Users/Jim Henry/AppData/Local/Packages/microsoft.windowscommunicationsapps_8wekyb3d8bbwe/LocalState/Files/S0/10/Attachments/A Right where you're supposed to be - Ran Register[165].epub
Sigil version: 1.4.3
Runtime Qt: 5.12.9
Compiled Qt: 5.12.9
System: Windows 10 (10.0)
Architecture: x86_64

**Comment by dougmassay** [comment]
Why on earth is an epub being stored/saved in the Microsoft Store app packaging area?

**Comment by jimhenry2** [comment]
Don’t know, it wasn’t  me.  Sent from Mail for Windows 10 From: Doug MassaySent: Sunday, March 7, 2021 9:47 AMTo: Sigil-Ebook/sigil-user-guideCc: jimhenry2; AuthorSubject: Re: [Sigil-Ebook/sigil-user-guide] Can't save (#3) Why on earth is an epub being stored/saved in the Microsoft Store app packaging area?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dougmassay** [comment]
Try saving it somewhere more reasonable/accessible like My Documents. How did you go about opening the epub from that location with Sigil?

**Comment by jimhenry2** [comment]
Easy. Selected ‘open’ and that list appeared with the correct files in it. How they got there is beyond me (we are dealing with MS here)’ Sent from Mail for Windows 10 From: Doug MassaySent: Sunday, March 7, 2021 10:29 AMTo: Sigil-Ebook/sigil-user-guideCc: jimhenry2; AuthorSubject: Re: [Sigil-Ebook/sigil-user-guide] Can't save (#3) Try saving it somewhere more reasonable/accessible like My Documents. How did you go about opening the epub from that location with Sigil?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by kevinhendricks** [comment]
This is not a sigil-user-guide issue at all.  This should have been done in the Sigil repo not here.  My guess is they double-clicked to launch Sigil directly from an e-mail attachment and then tried a Save.

Bad idea in general.

**Comment by kevinhendricks** [comment]
We could add to our check to see if the file exists to see if it is writeable and if not abort the save forcing a save as.

**Comment by dougmassay** [comment]
Selected 'Open' from what? A file browser? Another application? I'm just trying to figure out how an epub located that deeply in the Appstore directory structure was browsed to and launched in the first place.

Also curious about all the extra CSS coding showing up in your replies. Never seen that before.

**Comment by dougmassay** [comment]
@kevinhendricks : whoops! Hadn't even noticed this was from user guide repo.

**Comment by jimhenry2** [comment]
I’m confused. Selected open in Sigil; up comes a list of the epub files I have been lately working on; it was in saving that error messages showed up; only after posting  did I see that the files were not where I put them but in some strange folder. I have since moved the files and everything is working again. But I appreciate your help, extra csss inserted when I used caliber editor on the file, my own css stylesheet was removed.  Sent from Mail for Windows 10 From: Doug MassaySent: Sunday, March 7, 2021 10:39 AMTo: Sigil-Ebook/sigil-user-guideCc: jimhenry2; AuthorSubject: Re: [Sigil-Ebook/sigil-user-guide] Can't save (#3) Selected 'Open' from what? A file browser? Another application? I'm just trying to figure out how an epub located that deeply in the Appstore directory structure was browsed to and launched in the first place.Also curious about all the extra CSS coding showing up in your replies. Never seen that before.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by dougmassay** [comment]
Yes. But the epub wasn't born in the recently opened list. I'm trying to imagine how it was _initially_ found and opened in such an odd (and deep) place. I'm guessing that you initially opened the epub directly from an email attachment. That particular location seems to be associated with Windows' People/Mail/Calendar apps. In the future, just save any emailed epub attachments somewhere before trying to open/edit/save them with Sigil. Doing an Open With directly on an email attachment is not recommended for anything other than read-only previewing.
